name: "ErsatzTV"
version: "1.0.0"
slug: "ersatztv"
description: "ErsatzTV â€“ Virtual TV channel assembly and streaming"
url: "https://github.com/Thepowa753/hassio_ersatzTV"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
map:
  - media:rw
  - config:rw
ports:
  8409/tcp: 8409
ports_description:
  8409/tcp: "ErsatzTV Web Interface"
options:
  base_folder: "/media"
schema:
  base_folder: str
ingress: true
ingress_port: 8409
panel_icon: mdi:television-play
panel_title: ErsatzTV
